WIP

diff --git a/type/__directory/gencode-remote b/type/__directory/gencode-remote
--- a/type/__directory/gencode-remote
+++ b/type/__directory/gencode-remote
@@ -3,7 +3,7 @@
 # 2011-2013 Nico Schottelius (nico-cdist at schottelius.org)
 # 2013 Steven Armstrong (steven-cdist armstrong.cc)
 # 2014 Daniel Heule (hda at sfs.biz)
-# 2020 Dennis Camera (dennis.camera at riiengineering.ch)
+# 2020,2023 Dennis Camera (dennis.camera at riiengineering.ch)
 #
 # This file is part of skonfig-base.
 #
@@ -21,6 +21,8 @@
 # along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
 #
 
+. "${__type:?}/files/functions.sh"
+
 destination="/${__object_id:?}"
 state_should=$(cat "${__object:?}/parameter/state")
 type=$(cat "${__object:?}/explorer/type")
@@ -29,128 +31,171 @@ stat_file="${__object:?}/explorer/stat"
 # variable to keep track if we have to set directory attributes
 set_attributes=false
 
-mkdiropt=''
-[ -f "${__object:?}/parameter/parents" ] && mkdiropt='-p'
-
-recursive=''
-if [ -f "${__object:?}/parameter/recursive" ]
+recursive=
+if test -f "${__object:?}/parameter/recursive"
 then
-   recursive='-R'
-   # need to allways set attributes when recursive is given
-   # as we don't want to check all subfolders/files
-   set_attributes=true
+	recursive='-R'
+	# need to allways set attributes when recursive is given
+	# as we don't want to check all subfolders/files
+	set_attributes=true
 fi
 
 get_current_value() {
-   if [ -s "${stat_file}" ]
-   then
-      _name="$1"
-      _value="$2"
-      case ${_value}
-      in
-         [0-9]*)
-            _index=2
-         ;;
-         *)
-            _index=3
-         ;;
-      esac
-      awk -v name="${_name}" '{ if (1 == index($0, name ":")) { print $'${_index}' } }' "${stat_file}"
-      unset -v _name _value _index
-   fi
+	if test -s "${stat_file}"
+	then
+		awk -v name="$1" -v value="$2" '{
+			if (1 == index($0, name ":")) {
+				if (value ~ /^[0-9]+$/) {
+					print $2
+				} else {
+					print $3
+				}
+			}
+		}' "${stat_file}"
+	fi
 }
 
 set_group() {
-    echo "chgrp ${recursive} '$1' '${destination}'"
-    echo "chgrp ${recursive} '$1'" >>"${__messages_out:?}"
+	printf 'command -p chgrp %s%s %s\n' \
+		"${recursive:+${recursive} }" "$1" "$(shquot "${destination}")"
+	printf 'chgrp %s%s\n' \
+		"${recursive:+${recursive} }" "$1" >>"${__messages_out:?}"
 }
 
 set_owner() {
-    echo "chown ${recursive} '$1' '${destination}'"
-    echo "chown ${recursive} '$1'" >>"${__messages_out:?}"
+	# XXX: need to quote owner:group?
+
+	printf 'command -p chown %s%s %s\n' \
+		"${recursive:+${recursive} }" "$1" "$(shquot "${destination}")"
+	printf 'chown %s%s\n' \
+		"${recursive:+${recursive} }" "$1" >>"${__messages_out:?}"
 }
 
 set_mode() {
-    echo "chmod ${recursive} '$1' '${destination}'"
-    echo "chmod ${recursive} '$1'" >>"${__messages_out:?}"
+	printf 'command -p chmod %s%s %s\n' \
+		"${recursive:+${recursive} }" "$1" "$(shquot "${destination}")"
+	printf 'chmod %s%s\n' \
+		"${recursive:+${recursive} }" "$1" >>"${__messages_out:?}"
 }
 
 case ${state_should}
 in
-   (present|exists)
-      if [ "${type}" != 'directory' ]
-      then
-         set_attributes=true
-         if [ "${type}" != 'none' ]
-         then
-            # our destination is not a directory, remove whatever is there
-            # and then create our directory and set all attributes
-            echo "rm -f '${destination}'"
-            echo 'remove non directory' >>"${__messages_out:?}"
-         fi
-         echo "mkdir ${mkdiropt} '${destination}'"
-         echo 'create' >>"${__messages_out:?}"
-      elif [ "${state_should}" = 'exists' ]
-      then
-         # The type is directory and --state exists. We are done and do not
-         # check or set the attributes.
-         exit 0
-      fi
+	(present|exists)
+		if test "${type}" != 'directory'
+		then
+			set_attributes=true
+			if test "${type}" != 'none'
+			then
+				# our destination is not a directory, remove whatever is there
+				# and then create our directory and set all attributes
+				printf 'rm -f %s\n' "$(shquot "${destination}")"
+				echo "remove non directory" >>"${__messages_out:?}"
+			fi
 
-      # Note: Mode - needs to happen last as a chown/chgrp can alter mode by
-      # clearing S_ISUID and S_ISGID bits (see chown(2))
-      for attribute in group owner mode
-      do
-         if [ -f "${__object:?}/parameter/${attribute}" ]
-         then
-            value_should=$(cat "${__object:?}/parameter/${attribute}")
-            value_is=$(get_current_value "${attribute}" "${value_should}")
+			mkdiropt=
+			if test -f "${__object:?}/parameter/parents"
+			then
+				mkdiropt=' -p'
+			fi
 
-            # format mode in four digits => same as stat returns
-            if [ "${attribute}" = mode ]
-            then
-                # Convert to four-digit octal number (printf interprets
-                # strings with leading 0s as octal!)
-                value_should=$(printf '%04o' "0${value_should}")
-            fi
+			printf 'mkdir%s %s\n' "${mkdiropt}" "$(shquot "${destination}")"
+			echo create >>"${__messages_out:?}"
+		elif test "${state_should}" = 'exists'
+		then
+			# The type is directory and --state exists. We are done and do not
+			# check or set the attributes.
+			exit 0
+		fi
 
-            if ${set_attributes?} || [ "${value_should}" != "${value_is}" ]
-            then
-               "set_${attribute}" "${value_should}"
-            fi
-         fi
-      done
-      ;;
-   (pre-exists)
-      case ${type}
-      in
-         directory)
-            # all good
-            exit 0
-         ;;
-         none)
-            printf 'Directory "%s" does not exist\n' "${destination}" >&2
-            exit 1
-         ;;
-         file|symlink)
-            printf 'File "%s" exists and is a %s, but should be a directory\n' "${destination}" "${type}" >&2
-            exit 1
-         ;;
-         *)
-            printf 'File or directory "%s" is in an unknown state\n' "${destination}" >&2
-            exit 1
-         ;;
-      esac
-      ;;
-   (absent)
-      if [ "${type}" = 'directory' ]
-      then
-         echo "rm -rf '${destination}'"
-         echo remove >>"${__messages_out:?}"
-      fi
-      ;;
-   (*)
-      printf 'Invalid --state: %s\n' "${state_should}" >&2
-      exit 1
-      ;;
+		# Note: Mode - needs to happen last as a chown/chgrp can alter mode by
+		# clearing S_ISUID and S_ISGID bits (see chown(2))
+
+		if test -f "${__object:?}/parameter/owner"
+		then
+			owner_should=$(cat "${__object:?}/parameter/owner")
+			owner_is=$(get_current_value owner "${owner_should}")
+
+			if test -f "${__object:?}/parameter/group"
+			then
+				group_should=$(cat "${__object:?}/parameter/group")
+				group_is=$(get_current_value group "${group_should}")
+
+				if ${set_attributes?} || test "${group_is}" != "${group_should}"
+				then
+					own=:${group_should}
+				fi
+			fi
+
+			if ${set_attributes?} \
+				|| test -n "${own-}" \
+				|| test "${owner_is}" != "${owner_should}"
+			then
+
+				own=${owner_should}${own-}
+			fi
+
+			if test -n "${own-}"
+			then
+				set_owner "${own}"
+			fi
+		elif test -f "${__object:?}/parameter/group"
+		then
+			group_should=$(cat "${__object:?}/parameter/group")
+			group_is=$(get_current_value group "${group_should}")
+
+			if ${set_attributes?} || test "${group_should}" != "${group_is}"
+			then
+				set_group "${group_should}"
+			fi
+		fi
+
+		if test -f "${__object:?}/parameter/mode"
+		then
+			mode_should=$(cat "${__object:?}/parameter/mode")
+			mode_is=$(get_current_value mode "${mode_should}")
+
+			# Convert to four-digit octal number (printf interprets
+			# strings with leading 0s as octal!)
+			mode_should=$(printf '%04o' "0${mode_should}")
+
+			if ${set_attributes?} || test "${mode_should}" != "${mode_is}"
+			then
+				set_mode "${mode_should}"
+			fi
+		fi
+		;;
+	(pre-exists)
+		case ${type}
+		in
+			(directory)
+				# all good
+				exit 0
+				;;
+			(none)
+				printf 'Directory "%s" does not exist\n' "${destination}" >&2
+				exit 1
+				;;
+			(file|symlink)
+				printf 'File "%s" exists and is a %s, but should be a directory\n' "${destination}" "${type}" >&2
+				exit 1
+				;;
+			(*)
+				printf 'File or directory "%s" is in an unknown state\n' "${destination}" >&2
+				exit 1
+				;;
+		esac
+		;;
+	(absent)
+		case ${type}
+		in
+			(directory)
+				printf 'rm -R -f %s\n' "$(shquot "${destination}")"
+				echo remove >>"${__messages_out:?}"
+				;;
+		esac
+		;;
+	(*)
+		printf 'Invalid --state: %s\n' "${state_should}" >&2
+		exit 1
+		;;
 esac
diff --git a/type/__git/manifest b/type/__git/manifest
--- a/type/__git/manifest
+++ b/type/__git/manifest
@@ -18,42 +18,35 @@
 # along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
 #
 
-__package git --state present
-
-state_should=$(cat "${__object:?}/parameter/state")
-owner=$(cat "${__object:?}/parameter/owner")
-group=$(cat "${__object:?}/parameter/group")
-mode=$(cat "${__object:?}/parameter/mode")
-
-# Let __directory handle removal of git repos
+read -r state_should <"${__object:?}/parameter/state"
 
 case ${state_should}
 in
-    (present)
-        source=$(cat "${__object:?}/parameter/source")
-        case ${source}
-        in
-            (https://*)
-                os=$(cat "${__global:?}/explorer/os")
-                case ${os}
-                in
-                    (debian|devuan|ubuntu)
-                        __package_apt ca-certificates
-                        ;;
-                esac
-                ;;
-        esac
-        ;;
+	(present)
+		__package git
 
-    (absent)
-        __directory "${__object_id:?}" --state absent \
-            --owner "${owner}" \
-            --group "${group}" \
-            --mode "${mode}"
-        ;;
+		source=$(cat "${__object:?}/parameter/source")
+		case ${source}
+		in
+			(https://*)
+				os=$(cat "${__global:?}/explorer/os")
+				case ${os}
+				in
+					(debian|devuan|ubuntu)
+						__package_apt ca-certificates
+						;;
+				esac
+				;;
+		esac
+		;;
 
-    (*)
-        printf 'Invalid --state: %s\n' "${state_should}" >&2
-        exit 1
-        ;;
+	(absent)
+		# let __directory handle removal of git repos
+		__directory "${__object_id:?}" --state absent
+		;;
+
+	(*)
+		printf 'Invalid --state: %s\n' "${state_should}" >&2
+		exit 1
+		;;
 esac
diff --git a/type/__rsync/gencode-local b/type/__rsync/gencode-local
--- a/type/__rsync/gencode-local
+++ b/type/__rsync/gencode-local
@@ -26,18 +26,18 @@ EOF
 }
 
 command -v rsync >/dev/null 2>&1 || {
-    echo 'rsync is missing in local machine' >&2
+    echo 'rsync is not installed on the local machine' >&2
     exit 1
 }
 
 src=$(cat "${__object:?}/parameter/source")
 
 test -e "${src}" || {
-    echo "${src} not found" >&2
+    printf 'source not found: %s\n' "${src}" >&2
     exit 1
 }
 
-if [ -f "${__object:?}/parameter/destination" ]
+if test -s "${__object:?}/parameter/destination"
 then
     dst=$(cat "${__object:?}/parameter/destination")
 else
@@ -49,7 +49,7 @@ fi
 # because this is what you almost always want when
 # rsyncing two directories.
 
-if [ -d "${src}" ]
+if test -d "${src}"
 then
     case ${src}
     in
@@ -81,7 +81,7 @@ else
 	options='--links --perms --recursive --times'
 fi
 
-if [ -f "${__object:?}/parameter/option" ]
+if test -f "${__object:?}/parameter/option"
 then
     while read -r l
     do
@@ -93,24 +93,24 @@ then
     done <"${__object:?}/parameter/option"
 fi
 
-if [ -f "${__object:?}/parameter/owner" ] || [ -f "${__object:?}/parameter/group" ]
+if test -f "${__object:?}/parameter/owner" || test -f "${__object:?}/parameter/group"
 then
     options="${options} --chown="
 
-    if [ -f "${__object:?}/parameter/owner" ]
+    if test -f "${__object:?}/parameter/owner"
     then
         owner=$(cat "${__object:?}/parameter/owner")
         options="${options}$(shquot "${owner}")"
     fi
 
-    if [ -f "${__object:?}/parameter/group" ]
+    if test -f "${__object:?}/parameter/group"
     then
         group=$(cat "${__object:?}/parameter/group")
         options="${options}:$(shquot "${group}")"
     fi
 fi
 
-if [ -f "${__object:?}/parameter/mode" ]
+if test -f "${__object:?}/parameter/mode"
 then
     mode=$(cat "${__object:?}/parameter/mode")
     options="${options} --chmod=$(shquot "${mode}")"
