WIP

diff --git a/type/__package_dpkg/gencode-remote b/type/__package_dpkg/gencode-remote
--- a/type/__package_dpkg/gencode-remote
+++ b/type/__package_dpkg/gencode-remote
@@ -2,6 +2,7 @@
 #
 # 2013 Tomas Pospisek (tpo_deb at sourcepole.ch)
 # 2018 Thomas Eckert (tom at it-eckert.de)
+# 2024 Dennis Camera (dennis.camera at riiengineering.ch)
 #
 # This file is part of skonfig-base.
 #
@@ -27,29 +28,37 @@
 # to conflict with dpkg's --force options). But currently we don't
 # do any checks or --force'ing.
 #
-state=$(cat "${__object:?}/parameter/state")
+
+state_should=$(cat "${__object:?}/parameter/state")
 package=$(basename "${__object_id:?}")
-state_is=$(cat "${__object:?}/explorer/pkg_state")
-state_should=''
 
-[ "${state}" = "absent" ] || state_should="${package}"
-[ "${state_is}" = "${state_should}" ] && exit 0
-
-case ${state}
+case ${state_should}
 in
-    (present)
-        echo "dpkg --install /var/cache/apt/archives/${__object_id:?}"
-        echo 'installed' >>"${__messages_out:?}"
-        ;;
-    (absent)
-        [ -f "${__object:?}/parameter/purge-if-absent" ] \
-            && action='--purge' \
-            || action='--remove'
-        echo "dpkg ${action} ${__object_id%%_*}"
-        echo "removed (${action})" >>"${__messages_out:?}"
-        ;;
-    (*)
-        printf 'Invalid --state: %s\n' "${state}" >&2
-        exit 1
-        ;;
+	(present)
+		if test "$(cat "${__object:?}/explorer/pkg_state")" != "${package}"
+		then
+			echo "dpkg --install /var/cache/apt/archives/${package}"
+
+			echo installed >>"${__messages_out:?}"
+		fi
+		;;
+	(absent)
+		if test -s "${__object:?}/explorer/pkg_state"
+		then
+			if test -f "${__object:?}/parameter/purge-if-absent"
+			then
+				action='--purge'
+			else
+				action='--remove'
+			fi
+
+			echo "dpkg ${action} ${__object_id%%_*}"
+
+			echo "removed (${action})" >>"${__messages_out:?}"
+		fi
+		;;
+	(*)
+		printf 'Invalid --state: %s\n' "${state_should}" >&2
+		exit 1
+		;;
 esac
